#!/bin/bash


# grab latest tags
PHP_TAGS=$(curl 'https://registry.hub.docker.com/v2/repositories/library/php/tags?page_size=1024' | grep -Po "[0-9]+\.[0-9]+\.[0-9]+-apache" | sed 's/-apache//' | sort | uniq)
IS_MASTER_BUILD=$([ "$SOURCE_BRANCH" == "master" ] && echo 1 || echo 0)

echo "##### Build default image - ${IMAGE_NAME} #####"
docker build --build-arg PHP_VERSION_TAG=${PHP_VERSION_TAG} -f $DOCKERFILE_PATH -t ${IMAGE_NAME} .

if [ $IS_MASTER_BUILD -eq 1 ]; then

  for PHP_MINOR in $(echo "$PHP_TAGS" | grep -Po "^[0-9]+\.[0-9]+" | sort | uniq); do
    echo "##### Build ${PHP_MINOR} #####"
    docker build --build-arg PHP_VERSION_TAG=${PHP_MINOR}-apache -f ${DOCKERFILE_PATH} -t ${DOCKER_REPO}:${PHP_MINOR} .
  done

  for PHP_VERSION in $(echo "$PHP_TAGS"); do
    echo "##### Build $PHP_VERSION (x.y.z) #####"
    docker build --build-arg PHP_VERSION_TAG=${PHP_VERSION}-apache -f ${DOCKERFILE_PATH} -t ${DOCKER_REPO}:${PHP_VERSION} .
  done

else

  CURRENT_RELEASE=$(echo $SOURCE_BRANCH | cut -c2-)

  for PHP_MINOR in $(echo "$PHP_TAGS" | grep -Po "^[0-9]+\.[0-9]+" | sort | uniq); do
    SHORT_DOCKER_TAG=$(echo $CURRENT_RELEASE | cut -d'.' -f-2)
    CUSTOM_IMAGE_NAME="${DOCKER_REPO}:php${PHP_MINOR}-v${SHORT_DOCKER_TAG}"
    echo "##### Build $CUSTOM_IMAGE_NAME #####"
    docker build --build-arg PHP_VERSION_TAG=${PHP_MINOR}-apache -f ${DOCKERFILE_PATH} -t ${CUSTOM_IMAGE_NAME} .
  done

  for PHP_VERSION in $(echo "$PHP_TAGS"); do
    CUSTOM_IMAGE_NAME="${DOCKER_REPO}:php${PHP_VERSION}-v${CURRENT_RELEASE}"
    echo "##### Build $CUSTOM_IMAGE_NAME #####"
    docker build --build-arg PHP_VERSION_TAG=${PHP_VERSION}-apache -f ${DOCKERFILE_PATH} -t ${CUSTOM_IMAGE_NAME} .
  done

fi
