#!/bin/bash


docker build -f $DOCKERFILE_PATH -t ${IMAGE_NAME} .

if [ $DOCKER_TAG == "latest" ]; then
  docker build --build-arg PHP_VERSION_TAG=7.1-apache -f $DOCKERFILE_PATH -t $DOCKER_REPO:7.1-latest .
  docker build --build-arg PHP_VERSION_TAG=7.2-apache -f $DOCKERFILE_PATH -t $DOCKER_REPO:7.2-latest .
  docker build --build-arg PHP_VERSION_TAG=7.3-apache -f $DOCKERFILE_PATH -t $DOCKER_REPO:7.3-latest .
  docker build --build-arg PHP_VERSION_TAG=7.4-apache -f $DOCKERFILE_PATH -t $DOCKER_REPO:7.4-latest .
else
  docker build --build-arg PHP_VERSION_TAG=7.1-apache -f $DOCKERFILE_PATH -t $DOCKER_REPO:7.1-$DOCKER_TAG .
  docker build --build-arg PHP_VERSION_TAG=7.2-apache -f $DOCKERFILE_PATH -t $DOCKER_REPO:7.2-$DOCKER_TAG .
  docker build --build-arg PHP_VERSION_TAG=7.3-apache -f $DOCKERFILE_PATH -t $DOCKER_REPO:7.3-$DOCKER_TAG .
  docker build --build-arg PHP_VERSION_TAG=7.4-apache -f $DOCKERFILE_PATH -t $DOCKER_REPO:7.4-$DOCKER_TAG .
fi
