#!/bin/bash


IS_MASTER_BUILD=$([ "$SOURCE_BRANCH" == "master" ] && echo 1 || echo 0)
IS_RELEASE_BUILD=$((echo "$SOURCE_BRANCH" | grep -Pq "v[0-9]+\.[0-9]+\.[0-9]+") && echo 1 || echo 0)

# return list of "<phpFromSource>|<targetTag>" depending if we are building against master or a specific release
getBuildParams() {
  local RELEASE=$(echo $SOURCE_BRANCH | cut -c2-)
  local MAJOR_RELEASE=$(echo $RELEASE | cut -d'.' -f1)
  local MINOR_RELEASE=$(echo $RELEASE | cut -d'.' -f-2)
  local PHP_MINOR=""
  local PHP_TAGS=$(curl 'https://registry.hub.docker.com/v2/repositories/library/php/tags?page_size=1024' | grep -Po "[0-9]+\.[0-9]+\.[0-9]+-apache" | sed 's/-apache//' | sort | uniq)
  local PHP_VERSION=""

  for PHP_MINOR in $(echo "$PHP_TAGS" | grep -Po "^[0-9]+\.[0-9]+" | sort | uniq); do
    if [ $IS_MASTER_BUILD -eq 1 ]; then
      echo "${PHP_MINOR}-apache|php${PHP_MINOR}-master"
    elif [ $IS_RELEASE_BUILD -eq 1 ]; then
      echo "${PHP_MINOR}-apache|php${PHP_MINOR}-v${MINOR_RELEASE}"
      echo "${PHP_MINOR}-apache|php${PHP_MINOR}-v${RELEASE}"
    fi
  done

  for PHP_VERSION in $(echo "$PHP_TAGS"); do
    if [ $IS_RELEASE_BUILD -eq 1 ]; then
      echo "${PHP_VERSION}-apache|php${PHP_VERSION}-v${MINOR_RELEASE}"
      echo "${PHP_VERSION}-apache|php${PHP_VERSION}-v${RELEASE}"
    fi
  done
}
