#!/bin/bash


# grab latest tags
PHP_TAGS=$(curl 'https://registry.hub.docker.com/v2/repositories/library/php/tags?page_size=1024' | grep -Po "[0-9]+\.[0-9]+\.[0-9]+-apache" | sed 's/-apache//' | sort | uniq)

if [ $DOCKER_TAG == "latest" ]; then

  for PHP_MAJOR in $(echo "$PHP_TAGS" | grep -Po "^[0-9]+" | sort | uniq); do
    echo "##### Push ${PHP_MAJOR}-latest (x-latest) #####"
    docker push ${DOCKER_REPO}:${PHP_MAJOR}-latest
  done

  for PHP_MINOR in $(echo "$PHP_TAGS" | grep -Po "^[0-9]+\.[0-9]+" | sort | uniq); do
    echo "##### Push ${PHP_MINOR}-latest (x.y-latest) #####"
    docker push ${DOCKER_REPO}:${PHP_MINOR}-latest
  done

  for PHP_VERSION in $(echo "$PHP_TAGS"); do
    echo "##### Push $PHP_VERSION (x.y.z) #####"
    docker push ${DOCKER_REPO}:${PHP_VERSION}
  done

  #docker push $DOCKER_REPO:7.1-latest
  #docker push $DOCKER_REPO:7.2-latest
  #docker push $DOCKER_REPO:7.3-latest
  #docker push $DOCKER_REPO:7.4-latest
else

  for PHP_MAJOR in $(echo "$PHP_TAGS" | grep -Po "^[0-9]+" | sort | uniq); do
    echo "##### Push ${PHP_MAJOR}-${DOCKER_TAG} (phpVersion-basePhpApacheVersion) #####"
    docker push ${DOCKER_REPO}:${PHP_MAJOR}-${DOCKER_TAG}
  done

  for PHP_MINOR in $(echo "$PHP_TAGS" | grep -Po "^[0-9]+\.[0-9]+" | sort | uniq); do
    echo "##### Push ${PHP_MINOR}-latest (x.y-latest) #####"
    docker push ${DOCKER_REPO}:${PHP_MINOR}-${DOCKER_TAG}
  done

  for PHP_VERSION in $(echo "$PHP_TAGS"); do
    echo "##### Push $PHP_VERSION (x.y.z) #####"
    docker push ${DOCKER_REPO}:${PHP_VERSION}-${DOCKER_TAG}
  done

  #docker push $DOCKER_REPO:7.1-$DOCKER_TAG
  #docker push $DOCKER_REPO:7.2-$DOCKER_TAG
  #docker push $DOCKER_REPO:7.3-$DOCKER_TAG
  #docker push $DOCKER_REPO:7.4-$DOCKER_TAG
fi
