#!/bin/bash


set -e

if [ $DOCKER_TAG == "latest" ]; then
  docker push $IMAGE_NAME
  docker push $DOCKER_REPO:7.1-latest
  docker push $DOCKER_REPO:7.2-latest
  docker push $DOCKER_REPO:7.3-latest
  docker push $DOCKER_REPO:7.4-latest
else
  docker push $DOCKER_REPO:7.1-$DOCKER_TAG
  docker push $DOCKER_REPO:7.2-$DOCKER_TAG
  docker push $DOCKER_REPO:7.3-$DOCKER_TAG
  docker push $DOCKER_REPO:7.4-$DOCKER_TAG
fi
